


[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']



[[plugins]]
repo = 'Shougo/context_filetype.vim'



[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'



[[plugins]]
repo = 'Shougo/neomru.vim'



[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
on_event = 'BufRead'
hook_add = '''
nnoremap <silent> <Leader><C-f> :<C-u>DeniteBufferDir -split=vertical -vertical-preview -auto-action=preview -direction=topleft file<CR>
nnoremap <silent> <Leader><C-r> :<C-u>DeniteBufferDir -split=vertical -vertical-preview -auto-action=preview -direction=topleft file/rec<CR>
nnoremap <silent> <C-b>         :<C-u>Denite          -split=vertical -direction=topleft buffer file_mru<CR>

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  inoremap <silent><buffer><expr> <BS>    denite#do_map('move_up_path')
  nnoremap <silent><buffer><expr> <CR>    denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d       denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p       denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> i       denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> q       denite#do_map('quit')
  nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select').'j'
endfunction
'''
hook_post_source = '''
call denite#custom#var('file/rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#filter('matcher/ignore_globs', 'ignore_globs', ['.git', '.svn', 'node_modules'])
'''


