


#
# Syntax
#



[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'nginx'
[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = 'nginx'



#
# Color
#



[[plugins]]
repo = 'vim-scripts/Colour-Sampler-Pack'
hook_add = '''
colorscheme wuye
if &diff
  " colorscheme colorer
endif
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


[[plugins]]
repo = 'Shougo/context_filetype.vim'



