
#
# Syntax
#



[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'nginx'
[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = 'nginx'



#
# Color
#



[[plugins]]
repo = 'vim-scripts/Colour-Sampler-Pack'
hook_add = '''
colorscheme wuye
if &diff
  " colorscheme colorer
endif
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


[[plugins]]
repo = 'Shougo/context_filetype.vim'



[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
let g:airline#extensions#tabline#enabled = 0
let g:airline_theme='angr'
'''
[[plugins]]
repo = 'vim-airline/vim-airline-themes'




[[plugins]]
repo = 'sjl/gundo.vim'
hook_add = '''
let g:gundo_right = 1
nnoremap <F8> :GundoToggle<CR>
'''


